### ISSUE TITLE
Contribution: Add notes about using 'git submodule'

### ISSUE THREAD

**Issue by jplesnik** [sclorg/welcome#11]
### Description

Please add to [Contribution](https://github.com/sclorg/welcome/blob/master/contribution.md) using of `git submodule update --init`

**Comment by pkubatrh** [comment]
I think @Lupphes might have a working copy for the addition of this already.

**Comment by Lupphes** [comment]
I'm currently working on this issue, and it will be added very soon

**Comment by zmiklank** [comment]
The info about the submodule is now available in contribution.md.[1]

[1] https://github.com/sclorg/welcome/blob/ce08d84a8c3372188b6512e531bbe299ca9abfc8/contribution.md?plain=1#L24
