### ISSUE TITLE
Describe how to add new versions of containers

### ISSUE THREAD

**Issue by zmiklank** [sclorg/welcome#4]
- mention adding to build and push
- mention adjusting container-tests and openshift tests

**Comment by zmiklank** [comment]
+ add info about running tests
+ add info about configuring tests

**Comment by zmiklank** [comment]
- mention https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

**Comment by phracek** [comment]
@yselkowitz Can you please add there which labels are important from OpenShift 3 and even OpenShift 4 point of view.

**Comment by yselkowitz** [comment]
The aforementioned link describes pretty well the LABELs expected of RH container images.
